### ISSUE TITLE
Create metrics dashboard on Grafana

### ISSUE THREAD

**Issue by tienhngnguyen** [peterbangert/MP-DS#21]
A dashboard needs to be created which shows all metrics of the relevant tools on our Kubernetes Cluster

E.g.:

- Throughput on Kafka (messages/seconds)

- Resource consumption

- Available topics

- Messages in the topics

- Latency

The README.md file should be updated accordingly so that it can be reproduced/recreated by all team members any time

**Comment by pfisterb** [comment]
Done
