### ISSUE TITLE
Storing Flink formatted data in Database

### ISSUE THREAD

**Issue by sumitpaulde** [peterbangert/MP-DS#8]
Here we have to decide where should we store our table of contact persons, Reddis can be a problem because there are not any Flink_connector for Reddis. As per my research, I have found Casandra or MongoDB connector with Flink. We have to also remember that, when an infection event is generated we will query our whole DB to get all the contact-ids.

**Comment by pfisterb** [comment]
Redis is well suited for our use case since it's a lightweight key-value store. Jedis is a Java client for Redis and works well in a Flink application: https://github.com/redis/jedis

**Comment by peterbangert** [comment]
done https://github.com/peterbangert/MP-DS/pull/11
